"""Replaceable storage boundary. Business code never receives SQL or a connection."""

from datetime import datetime
from typing import Protocol
from uuid import UUID

from app.analytics.models import AnalyticsSummary, ConversationEvent, EventPage, EventQuery


class EventStore(Protocol):
    def initialize(self) -> None: ...
    def probe(self) -> None: ...
    def append(self, event: ConversationEvent) -> int: ...
    def append_many(self, events: list[ConversationEvent]) -> int: ...
    def get_event(self, event_id: UUID) -> ConversationEvent | None: ...
    def get_session_events(
        self, session_id: str, *, limit: int = 100, offset: int = 0
    ) -> EventPage: ...
    def query_events(self, query: EventQuery) -> EventPage: ...
    def get_recent_events(self, limit: int = 100) -> EventPage: ...
    def summary(self, query: EventQuery) -> AnalyticsSummary: ...
    def analytics_snapshot(self, query: EventQuery) -> list[ConversationEvent]: ...
    def source_history_starts(self, query: EventQuery) -> dict[str, datetime]: ...
